@startuml
class com.auction.project.Entities.VehicleItem {
- String make
+ String getDetails()
}


class com.auction.project.Server.ServerApp {
+ {static} void main(String[])
}

class com.auction.project.Client.ClientHandler {
- ObjectInputStream in
- Consumer<Response> onResponse
+ void setOnResponse(Consumer<Response>)
+ void run()
}


class com.auction.project.Exception.AuctionClosedException {
}
class com.auction.project.Server.SocketServer {
- int port
+ {static} List<ClientHandler> clients
- ExecutorService pool
+ void start()
+ {static} void broadcast(Object)
+ {static} void main(String[])
}


class com.auction.project.Packets.BidRequest {
- {static} long serialVersionUID
- double amount
- String username
- Instant timestamp
+ double getAmount()
+ String getUsername()
+ Instant getTimestamp()
+ void setAmount(double)
+ String toString()
}


class com.auction.project.Entities.Admin {
+ void cancelAuction(Auction)
}

class com.auction.project.Entities.ElectronicsItem {
- String brand
+ String getDetails()
}


class com.auction.project.Packets.Response {
- {static} long serialVersionUID
- String type
- String message
+ String getType()
+ String getMessage()
+ void setType(String)
+ void setMessage(String)
+ String toString()
}


interface com.auction.project.Observer.Observer {
~ void update(int,double,String)
}

class com.auction.project.Packets.LoginRequest {
- {static} long serialVersionUID
- String username
- String password
+ String getUsername()
+ String getPassword()
+ String toString()
}


class com.auction.project.Manager.AuctionManager {
- Map<Integer,Auction> auctions
+ {static} AuctionManager getInstance()
+ void addAuction(Auction)
+ Auction getAuction(int)
+ Collection<Auction> getAllAuctions()
}


class com.auction.project.Manager.AuctionManager$Holder {
- {static} AuctionManager INSTANCE
}

class com.auction.project.Entities.Seller {
+ Auction createAuction(Item,LocalDateTime,LocalDateTime,double)
}

class com.auction.project.Entities.Auction {
- {static} long serialVersionUID
- LocalDateTime startTime
- LocalDateTime endTime
- double currentPrice
- AuctionStatus status
- List<Observer> observers
- List<BidTransaction> transactions
- Item item
+ void placeBid(Bidder,double)
+ void setStatus(AuctionStatus)
+ int getId()
+ double getCurrentPrice()
+ void registerObserver(Observer)
+ void removeObserver(Observer)
+ void notifyObservers()
}


enum com.auction.project.Entities.enums.AuctionStatus {
+  OPEN
+  RUNNING
+  FINISHED
+  PAID
+  CANCELED
}

class com.auction.project.Manager.BidTransaction {
- double amount
- LocalDateTime timestamp
- Bidder bidder
+ double getAmount()
+ Bidder getBidder()
}


abstract class com.auction.project.Entities.Entity {
- {static} long serialVersionUID
- {static} int idCounter
# int id
# LocalDateTime createdAt
+ int getId()
}


abstract class com.auction.project.Entities.User {
# String username
# String passwordHash
# String email
+ String getUsername()
+ boolean login()
+ void logout()
}


class com.auction.project.Entities.ArtItem {
- String artist
- int year
+ String getDetails()
}


class com.auction.project.Entities.Bidder {
- List<BidTransaction> biddingHistory
+ void placeBid(Auction,double)
+ void update(int,double,String)
+ void addTransaction(BidTransaction)
}


abstract class com.auction.project.Entities.Item {
# String name
# String description
# double startPrice
+ {abstract}String getDetails()
}


class com.auction.project.Client.ClientApp {
+ {static} void main(String[])
}

class com.auction.project.Server.DataStorage {
- {static} Logger LOG
- {static} DateTimeFormatter BACKUP_FMT
- {static} Path DATA_DIR
- {static} Path BACKUP_DIR
- {static} Path USER_FILE
- {static} Path BID_FILE
- {static} java.util.concurrent.locks.ReentrantLock LOCK
- {static} ScheduledExecutorService autoSaveScheduler
+ {static} void saveUsers(java.util.concurrent.ConcurrentHashMap<String,String>)
+ {static} java.util.concurrent.ConcurrentHashMap<String,String> loadUsers()
+ {static} void saveBids(List<BidRequest>)
+ {static} List<BidRequest> loadBids()
+ {static} void startAutoSave(java.util.concurrent.ConcurrentHashMap<String,String>,List<BidRequest>,long)
+ {static} void stopAutoSave(java.util.concurrent.ConcurrentHashMap<String,String>,List<BidRequest>)
- {static} void ensureDirs()
- {static} void backupIfExists(Path)
- {static} void atomicWrite(Path,Serializable)
}


class com.auction.project.Factory.UserFactory {
+ {static} User createUser(String,String,String)
}

class com.auction.project.Server.ClientHandler {
- Socket socket
- ObjectInputStream in
- ObjectOutputStream out
- {static} ConcurrentHashMap<String,String> users
- {static} double currentBid
- {static} List<BidRequest> bidHistory
- {static} Object BID_LOCK
+ {static} ConcurrentHashMap<String,String> getUsers()
+ {static} List<BidRequest> getBidHistory()
+ {static} double getCurrentBid()
+ void run()
- void handleLogin(LoginRequest)
- void handleBid(BidRequest)
+ void send(Object)
- void closeResources()
}


class com.auction.project.Client.ClientService {
- {static} ClientService instance
- Socket socket
- ObjectOutputStream out
- ObjectInputStream in
- BiConsumer<Integer,Double> onPriceUpdate
+ {static} ClientService getInstance()
+ void connect(String,int)
- void startListening()
+ void setOnPriceUpdate(BiConsumer<Integer,Double>)
+ String placeBid(int,double)
+ void createLocalRecord(Bidder,double)
+ void disconnect()
}


class com.auction.project.Exception.InvalidBidException {
}
interface com.auction.project.Observer.Subject {
~ void registerObserver(Observer)
~ void removeObserver(Observer)
~ void notifyObservers()
}

class com.auction.project.Factory.ItemFactory {
+ {static} Item createItem(String,String,double,String)
}

class com.auction.project.Client.SocketClient {
- Socket socket
- ObjectOutputStream out
- ObjectInputStream in
- ClientHandler handler
- String username
+ void setOnResponse(Consumer<Response>)
+ void send(Object)
+ void login(String,String)
+ void bid(double)
+ void close()
}




com.auction.project.Entities.Item <|-- com.auction.project.Entities.VehicleItem
com.auction.project.Client.Thread <|-- com.auction.project.Client.ClientHandler
com.auction.project.Exception.Exception <|-- com.auction.project.Exception.AuctionClosedException
java.io.Serializable <|.. com.auction.project.Packets.BidRequest
com.auction.project.Entities.User <|-- com.auction.project.Entities.Admin
com.auction.project.Entities.Item <|-- com.auction.project.Entities.ElectronicsItem
java.io.Serializable <|.. com.auction.project.Packets.Response
java.io.Serializable <|.. com.auction.project.Packets.LoginRequest
com.auction.project.Manager.AuctionManager +.. com.auction.project.Manager.AuctionManager$Holder
com.auction.project.Entities.User <|-- com.auction.project.Entities.Seller
com.auction.project.Entities.Subject <|.. com.auction.project.Entities.Auction
java.io.Serializable <|.. com.auction.project.Entities.Auction
com.auction.project.Entities.Entity <|-- com.auction.project.Entities.Auction
java.io.Serializable <|.. com.auction.project.Entities.Entity
com.auction.project.Entities.Entity <|-- com.auction.project.Entities.User
com.auction.project.Entities.Item <|-- com.auction.project.Entities.ArtItem
com.auction.project.Observer.Observer <|.. com.auction.project.Entities.Bidder
com.auction.project.Entities.User <|-- com.auction.project.Entities.Bidder
com.auction.project.Entities.Entity <|-- com.auction.project.Entities.Item
com.auction.project.Server.Thread <|-- com.auction.project.Server.ClientHandler
com.auction.project.Exception.Exception <|-- com.auction.project.Exception.InvalidBidException
@enduml