<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.auction.project</groupId>
        <artifactId>Dau_gia_ban3</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>auction-common</artifactId>

    <dependencies>
        <!-- Common cần Gson để parse Packets -->
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>${gson.version}</version>
        </dependency>
    </dependencies>
</project>